In [ ]:
import json
import pandas as pd #importing required modules

In [ ]:
f = open(r'C:\Users\Suryansh\Documents\gitsql\Python-for-DE-Advanced\10_Pandas\Dataset\orders_ETL.json')
data = json.load(f)    #cant convert the json document directly in the dataframe becuz of messy data
data

[{'order_id': 1,
  'order_date': '2024-01-10',
  'total_amount': 200.5,
  'customer': {'customer_id': 101,
   'name': 'John Doe',
   'email': 'johndoe@example.com',
   'address': '123 Main StSpringfield'},
  'products': [{'product_id': 'P01',
    'name': 'Wireless Mouse',
    'category': 'Electronics',
    'price': 25.0,
    'quantity': 2},
   {'product_id': 'P02',
    'name': 'Bluetooth Keyboard',
    'category': 'Electronics',
    'price': 45.0,
    'quantity': 1}]},
 {'order_id': 2,
  'order_date': '2024-01-12',
  'total_amount': 150.0,
  'customer': {'customer_id': 102,
   'name': 'Jane Smith',
   'email': 'janesmith@example.com',
   'address': '456 Oak StSpringfield'},
  'products': [{'product_id': 'P03',
    'name': 'Laptop Stand',
    'category': 'Electronics',
    'price': 75.0,
    'quantity': 1}]},
 {'order_id': 3,
  'order_date': '2024-01-12',
  'total_amount': 120.0,
  'customer': {'customer_id': 103,
   'name': 'Alice Johnson',
   'email': 'alicejohnson@example.com',
   'address': '789 Birch StSpringfield'},
  'products': [{'product_id': 'P04',
    'name': 'Gaming Headset',
    'category': 'Electronics',
    'price': 60.0,
    'quantity': 2}]},
 {'order_id': 4,
  'order_date': '2024-01-13',
  'total_amount': 300.5,
  'customer': {'customer_id': 101,
   'name': 'John Doe',
   'email': 'johndoe@example.com',
   'address': '123 Main StSpringfield'},
  'products': [{'product_id': 'P01',
    'name': 'Wireless Mouse',
    'category': 'Electronics',
    'price': 25.0,
    'quantity': 3},
   {'product_id': 'P02',
    'name': 'Bluetooth Keyboard',
    'category': 'Electronics',
    'price': 45.0,
    'quantity': 2}]},
 {'order_id': 5,
  'order_date': '2024-01-14',
  'total_amount': 180.0,
  'customer': {'customer_id': 104,
   'name': 'Bob Brown',
   'email': 'bobbrown@example.com',
   'address': '101 Maple StSpringfield'},
  'products': [{'product_id': 'P03',
    'name': 'Laptop Stand',
    'category': 'Electronics',
    'price': 75.0,
    'quantity': 1},
   {'product_id': 'P04',
    'name': 'Gaming Headset',
    'category': 'Electronics',
    'price': 60.0,
    'quantity': 1}]},
 {'order_id': 6,
  'order_date': '2024-01-14',
  'total_amount': 250.0,
  'customer': {'customer_id': 105,
   'name': 'Sania',
   'email': 'sania@example.com',
   'address': '102 Pine StSpringfield'},
  'products': [{'product_id': 'P01',
    'name': 'Wireless Mouse',
    'category': 'Electronics',
    'price': 25.0,
    'quantity': 2},
   {'product_id': 'P02',
    'name': 'Bluetooth Keyboard',
    'category': 'Electronics',
    'price': 45.0,
    'quantity': 2},
   {'product_id': 'P04',
    'name': 'Gaming Headset',
    'category': 'Electronics',
    'price': 60.0,
    'quantity': 1}]},
 {'order_id': 7,
  'order_date': '2024-01-16',
  'total_amount': 180.0,
  'customer': {'customer_id': 106,
   'name': 'Rohit',
   'email': 'rohit@example.com',
   'address': '103 Cedar StSpringfield'},
  'products': [{'product_id': 'P02',
    'name': 'Bluetooth Keyboard',
    'category': 'Electronics',
    'price': 45.0,
    'quantity': 2},
   {'product_id': 'P05',
    'name': 'Desk Organizer',
    'category': 'Furniture',
    'price': 30.0,
    'quantity': 1}]},
 {'order_id': 8,
  'order_date': '2024-01-16',
  'total_amount': 230.0,
  'customer': {'customer_id': 107,
   'name': 'Nina Patel',
   'email': 'ninapatel@example.com',
   'address': '104 Birch StSpringfield'},
  'products': [{'product_id': 'P01',
    'name': 'Wireless Mouse',
    'category': 'Electronics',
    'price': 25.0,
    'quantity': 3},
   {'product_id': 'P03',
    'name': 'Laptop Stand',
    'category': 'Electronics',
    'price': 75.0,
    'quantity': 1}]},
 {'order_id': 9,
  'order_date': '2024-01-17',
  'total_amount': 310.0,
  'customer': {'customer_id': 108,
   'name': 'Tom Harris',
   'email': 'tomharris@example.com',
   'address': '105 Oak StSpringfield'},
  'products': [{'product_id': 'P04',
    'name': 'Gaming Headset',
    'category': 'Electronics',
    'price': 60.0,
    'quantity': 2},
   {'product_id': 'P02',
    'name': 'Bluetooth Keyboard',
    'category': 'Electronics',
    'price': 45.0,
    'quantity': 2}]},
 {'order_id': 10,
  'order_date': '2024-01-18',
  'total_amount': 130.0,
  'customer': {'customer_id': 109,
   'name': 'Eva Lee',
   'email': 'evalee@example.com',
   'address': '106 Elm StSpringfield'},
  'products': [{'product_id': 'P05',
    'name': 'Desk Organizer',
    'category': 'Furniture',
    'price': 30.0,
    'quantity': 1},
   {'product_id': 'P03',
    'name': 'Laptop Stand',
    'category': 'Electronics',
    'price': 75.0,
    'quantity': 1}]},
 {'order_id': 11,
  'order_date': '2024-01-18',
  'total_amount': 250.0,
  'customer': {'customer_id': 101,
   'name': 'John Doe',
   'email': 'johndoe@example.com',
   'address': '123 Main StSpringfield'},
  'products': [{'product_id': 'P04',
    'name': 'Gaming Headset',
    'category': 'Electronics',
    'price': 60.0,
    'quantity': 2},
   {'product_id': 'P02',
    'name': 'Bluetooth Keyboard',
    'category': 'Electronics',
    'price': 45.0,
    'quantity': 2}]},
 {'order_id': 12,
  'order_date': '2024-01-19',
  'total_amount': 180.0,
  'customer': {'customer_id': 103,
   'name': 'Alice Johnson',
   'email': 'alicejohnson@example.com',
   'address': '789 Birch StSpringfield'},
  'products': [{'product_id': 'P01',
    'name': 'Wireless Mouse',
    'category': 'Electronics',
    'price': 25.0,
    'quantity': 2},
   {'product_id': 'P05',
    'name': 'Desk Organizer',
    'category': 'Furniture',
    'price': 30.0,
    'quantity': 1}]}]

In [ ]:
order_id = []  #creating lists to store ideal data in each list
order_date = []  
total_amount = []
quantity = []
customer_id = []
product_id = []
product_name = []
category = []
price = []
cust_id = []
customer_name = []
email = []
address = []

for orders in data:   #using loop to append data
    cust_id.append(orders['customer']['customer_id'])  #data for customer table
    customer_name.append(orders['customer']['name'])
    email.append(orders['customer']['email'])          
    address.append(orders['customer']['address'])
    for product in orders['products']: #loop for orders and products table
        product_id.append(product['product_id']) 
        quantity.append(product['quantity'])
        order_id.append(orders['order_id'])
        order_date.append(orders['order_date'])
        total_amount.append(orders['total_amount'])
        customer_id.append(orders['customer']['customer_id'])
        product_name.append(product['name'])
        category.append(product['category'])
        price.append(product['price'])

df_orders = pd.DataFrame({           #creating dataframe for orders table
    'customer_id': customer_id,    
    'order_id' :order_id,
    'product_id': product_id,
    'order_date': order_date,
    'total_amount': total_amount,
    'quantity': quantity
})

df_products = pd.DataFrame({          #creating dataframe for products table
    'product_id' : product_id,
    'product_name' : product_name,
    'category': category,
    'price': price
})

df_customers = pd.DataFrame({        #creating dataframe for customers table
    'customer_id': cust_id,
    'customer_name' :customer_name,
    'email': email,
    'address': address
})

df_customers

,customer_id,customer_name,email,address
0,101,John Doe,johndoe@example.com,123 Main StSpringfield
1,102,Jane Smith,janesmith@example.com,456 Oak StSpringfield
2,103,Alice Johnson,alicejohnson@example.com,789 Birch StSpringfield
3,101,John Doe,johndoe@example.com,123 Main StSpringfield
4,104,Bob Brown,bobbrown@example.com,101 Maple StSpringfield
5,105,Sania,sania@example.com,102 Pine StSpringfield
6,106,Rohit,rohit@example.com,103 Cedar StSpringfield
7,107,Nina Patel,ninapatel@example.com,104 Birch StSpringfield
8,108,Tom Harris,tomharris@example.com,105 Oak StSpringfield
9,109,Eva Lee,evalee@example.com,106 Elm StSpringfield
10,101,John Doe,johndoe@example.com,123 Main StSpringfield
11,103,Alice Johnson,alicejohnson@example.com,789 Birch StSpringfield

In [ ]:
df_customers.drop_duplicates(subset='customer_id', keep='last', inplace=True)  #removing duplicates from products and customers table
df_customers.reset_index(drop=True, inplace=True)
df_products.drop_duplicates(subset='product_id', keep='last', inplace=True)
df_products.reset_index(drop=True, inplace=True)
df_products

  product_id        product_name     category  price
0        P03        Laptop Stand  Electronics   75.0
1        P04      Gaming Headset  Electronics   60.0
2        P02  Bluetooth Keyboard  Electronics   45.0
3        P01      Wireless Mouse  Electronics   25.0
4        P05      Desk Organizer    Furniture   30.0

In [ ]:
from sqlalchemy import create_engine, text   

engine = create_engine(   #connecting to the database where we want to load the table
    "mssql+pyodbc://@DESKTOP-5K9N4EA\\SQLEXPRESS/SalesDB"   
    "?driver=ODBC+Driver+18+for+SQL+Server"
    "&trusted_connection=yes"
    "&TrustServerCertificate=yes"
)

In [ ]:
df_orders.to_sql(name='Orders_new', con= engine, index=False, if_exists='replace')    #loading the tables to the database
df_customers.to_sql(name='Customers_new', con= engine, index=False, if_exists='replace')
df_products.to_sql(name='Products_new', con= engine, index=False, if_exists='replace')

5